config/routes.rb
Rails.application.routes.draw do
  get 'stocks/search'
  get 'my_portfolio', to:'customers#my_portfolio'
  get 'search_stock', to: 'stocks#search'
  resources :customers, only: [ :index ]
  devise_for :customers, controllers: {
    registrations: 'customers/registrations'
  }
  root 'welcome#index'
  # For details on the DSL available within this file, see https://guides.rubyonrails.org/routing.html
end

app/models/application_record.rb
class ApplicationRecord < ActiveRecord::Base
  self.abstract_class = true
end

app/models/customer.rb
class Customer < ApplicationRecord
  # Include default devise modules. Others available are:
  # :confirmable, :lockable, :timeoutable, :trackable and :omniauthable
  devise :database_authenticatable, :registerable,
         :recoverable, :rememberable, :validatable
end

app/models/stock.rb
class Stock < ApplicationRecord

  def self.new_lookup ticker_symbol
    begin
      client = IEX::Api::Client.new()
      new(ticker_symbol: ticker_symbol, 
          name: client.company(ticker_symbol).company_name,
          last_price: client.price(ticker_symbol))
    rescue
    end
  end
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
  before_action :authenticate_customer!
end

app/controllers/customers/confirmations_controller.rb
# frozen_string_literal: true

class Customers::ConfirmationsController < Devise::ConfirmationsController
  # GET /resource/confirmation/new
  # def new
  #   super
  # end

  # POST /resource/confirmation
  # def create
  #   super
  # end

  # GET /resource/confirmation?confirmation_token=abcdef
  # def show
  #   super
  # end

  # protected

  # The path used after resending confirmation instructions.
  # def after_resending_confirmation_instructions_path_for(resource_name)
  #   super(resource_name)
  # end

  # The path used after confirmation.
  # def after_confirmation_path_for(resource_name, resource)
  #   super(resource_name, resource)
  # end
end

app/controllers/customers/omniauth_callbacks_controller.rb
# frozen_string_literal: true

class Customers::OmniauthCallbacksController < Devise::OmniauthCallbacksController
  # You should configure your model like this:
  # devise :omniauthable, omniauth_providers: [:twitter]

  # You should also create an action method in this controller like this:
  # def twitter
  # end

  # More info at:
  # https://github.com/heartcombo/devise#omniauth

  # GET|POST /resource/auth/twitter
  # def passthru
  #   super
  # end

  # GET|POST /users/auth/twitter/callback
  # def failure
  #   super
  # end

  # protected

  # The path used when OmniAuth fails
  # def after_omniauth_failure_path_for(scope)
  #   super(scope)
  # end
end

app/controllers/customers/passwords_controller.rb
# frozen_string_literal: true

class Customers::PasswordsController < Devise::PasswordsController
  # GET /resource/password/new
  # def new
  #   super
  # end

  # POST /resource/password
  # def create
  #   super
  # end

  # GET /resource/password/edit?reset_password_token=abcdef
  # def edit
  #   super
  # end

  # PUT /resource/password
  # def update
  #   super
  # end

  # protected

  # def after_resetting_password_path_for(resource)
  #   super(resource)
  # end

  # The path used after sending reset password instructions
  # def after_sending_reset_password_instructions_path_for(resource_name)
  #   super(resource_name)
  # end
end

app/controllers/customers/registrations_controller.rb
# frozen_string_literal: true

class Customers::RegistrationsController < Devise::RegistrationsController
  # before_action :configure_sign_up_params, only: [:create]
  # before_action :configure_account_update_params, only: [:update]

  #
  # GET /resource/sign_up
  # def new
  #   super
  # end

  # POST /resource
  def create
    super
  end

  # GET /resource/edit
  # def edit
  #   super
  # end

  # PUT /resource
  # def update
  #   super
  # end

  # DELETE /resource
  # def destroy
  #   super
  # end

  # GET /resource/cancel
  # Forces the session data which is usually expired after sign
  # in to be expired now. This is useful if the user wants to
  # cancel oauth signing in/up in the middle of the process,
  # removing all OAuth session data.
  # def cancel
  #   super
  # end

  # protected

  # If you have extra params to permit, append them to the sanitizer.
  # def configure_sign_up_params
  #   devise_parameter_sanitizer.permit(:sign_up, keys: [:attribute])
  # end

  # If you have extra params to permit, append them to the sanitizer.
  # def configure_account_update_params
  #   devise_parameter_sanitizer.permit(:account_update, keys: [:attribute])
  # end

  # The path used after sign up.
  # def after_sign_up_path_for(resource)
  #   super(resource)
  # end

  # The path used after sign up for inactive accounts.
  # def after_inactive_sign_up_path_for(resource)
  #   super(resource)
  # end
end

app/controllers/customers/sessions_controller.rb
# frozen_string_literal: true

class Customers::SessionsController < Devise::SessionsController
  # before_action :configure_sign_in_params, only: [:create]

  # GET /resource/sign_in
  def new
    super
    flash.now[:notice] = 'hmm'
  end

  # POST /resource/sign_in
  def create
    super
    flash.now[:notice] = 'hmm very descriptive message'
  end

  # DELETE /resource/sign_out
  # def destroy
  #   super
  # end

  # protected

  # If you have extra params to permit, append them to the sanitizer.
  # def configure_sign_in_params
  #   devise_parameter_sanitizer.permit(:sign_in, keys: [:attribute])
  # end
end

app/controllers/customers/unlocks_controller.rb
# frozen_string_literal: true

class Customers::UnlocksController < Devise::UnlocksController
  # GET /resource/unlock/new
  # def new
  #   super
  # end

  # POST /resource/unlock
  # def create
  #   super
  # end

  # GET /resource/unlock?unlock_token=abcdef
  # def show
  #   super
  # end

  # protected

  # The path used after sending unlock password instructions
  # def after_sending_unlock_instructions_path_for(resource)
  #   super(resource)
  # end

  # The path used after unlocking the resource
  # def after_unlock_path_for(resource)
  #   super(resource)
  # end
end

app/controllers/customers_controller.rb
class CustomersController < ApplicationController
  def index

  end

  def my_portfolio
  end
end

app/controllers/stocks_controller.rb
class StocksController < ApplicationController
  def search
    unless params[:stock].blank?
      @stock = Stock.new_lookup params[:stock] 
      if @stock
        respond_to do |format|
          format.js { render partial: 'customers/search_results' }
        end
      else
        respond_to do |format|
          flash.now[:notice] = 'please enter a valid symbol' 
          format.js { render partial: 'customers/search_results' }
        end
      end
    else
      respond_to do |format|
        flash.now[:notice] = 'please enter symbol to search'
        format.js { render partial: 'customers/search_results' }
      end
    end

  end
end

app/controllers/welcome_controller.rb
class WelcomeController < ApplicationController
  def index
  end
end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/customers_helper.rb
module CustomersHelper
end

app/helpers/stocks_helper.rb
module StocksHelper
end

app/helpers/welcome_helper.rb
module WelcomeHelper
end

app/views/customers/_search_display.html.erb
<% if @stock %>
  <div class='card card-header results-block'>
    <strong>Symbol: </strong> <%= @stock.ticker_symbol %>
    <strong>Name: </strong> <%= @stock.name %>
    <strong>Price: </strong> <%= @stock.last_price %>
  </div>
<% end %>

app/views/customers/_search_results.js.erb
document.querySelector('#search_results').innerHTML = '<%= @stock ? (j render partial: 'customers/search_display') : (j render partial: 'layouts/notifications') %>'

app/views/customers/index.html.erb
<h1> index of customers </h1>

app/views/customers/my_portfolio.html.erb
<div class='container'>
  <h1>My Portfolio</h1>

  <div class="search-area">
    <h3>Search stocks</h3>
    <%= form_tag search_stock_path, method: :get, remote: true do %>
      <div class='form-group row'>
        <div class='col-sm-9'>
          <%= text_field_tag :stock, params[:stock], placeholder: "Stock ticker simbol", autofocus: true, 
            class: 'form-control form-control-large' %>
        </div>
        <div class='col-sm-3'>
          <%= button_tag type: :submit, class: 'btn btn-success' do %>
            <%= 'Search' %>
          <% end %>
        </div>
      </div>
    <% end %>
  </div>
  <div id='search_results'></div>
</div>

app/views/customers/shared/_error_messages.html.erb
<% if resource.errors.any? %>
  <div class="d-flex justify-content-center">
    <button type="button" id='exampleButton' class="btn btn-warning"" data-bs-toggle="modal"
                                 data-bs-target="#exampleModal">what went wrong?</button>
  </div>

<!-- Modal -->
  <div class="modal fade" id="exampleModal" tabindex="-1" aria-labelledby="exampleModalLabel" aria-hidden="true">
    <div class="modal-dialog">
      <div class="modal-content">
        <div class="modal-header bg-light">
          <h5 class="modal-title" id="exampleModalLabel">
            <%= I18n.t("errors.messages.not_saved",
                       count: resource.errors.count,
                       resource: resource.class.model_name.human.downcase)
            %>
          </h5>
        </div>
        <div id="error_explanation" class="modal-body">
          <ul>
            <% resource.errors.full_messages.each do |message| %>
              <li><%= message %></li>
            <% end %>
          </ul>
        </div>
        <div class="modal-footer bg-light">
          <button type="button" class="btn btn-warning" data-bs-dismiss="modal">Close</button>
        </div>
      </div>
    </div>
  </div>
<% end %>

app/views/customers/shared/_links.html.erb
<div class="container">
  <ul class="nav justify-content-center">
    <%- if controller_name != 'sessions' %>
      <li class="nav-item">
        <%= link_to "Log in", new_session_path(resource_name), class: "nav-link btn-outline-success" %>
      </li>
    <% end %>

    <%- if devise_mapping.registerable? && controller_name != 'registrations' %>
      <li class="nav-item">
        <%= link_to "Sign up", new_registration_path(resource_name), class: "nav-link btn-outline-success" %>
      </li>
    <% end %>

    <%- if devise_mapping.recoverable? && controller_name != 'passwords' && controller_name != 'registrations' %>
      <li class="nav-item">
        <%= link_to "Forgot your password?", new_password_path(resource_name), class: "nav-link btn-outline-success" %>
      </li>
    <% end %>

    <%- if devise_mapping.confirmable? && controller_name != 'confirmations' %>
      <li class="nav-item">
        <%= link_to "Didn't receive confirmation instructions?", new_confirmation_path(resource_name), class: "nav-link btn-outline-success" %>
      </li>
    <% end %>

    <%- if devise_mapping.lockable? && resource_class.unlock_strategy_enabled?(:email) && controller_name != 'unlocks' %>
      <li class="nav-item">
        <%= link_to "Didn't receive unlock instructions?", new_unlock_path(resource_name), class: "nav-link btn-outline-success" %>
      </li>
    <% end %>

    <%- if devise_mapping.omniauthable? %>
      <%- resource_class.omniauth_providers.each do |provider| %>
      <li class="nav-item">
        <%= link_to "Sign in with #{OmniAuth::Utils.camelize(provider)}", omniauth_authorize_path(resource_name, provider), class: "nav-link btn-outline-success" %>
      </li>
      <% end %>
    <% end %>
  </ul>
</div>

app/views/layouts/_navbar.html.erb
<nav class="navbar navbar-expand-lg navbar-light bg-light">
  <div class="container-fluid container">
    <a class="navbar-brand" href="#">Navbar</a>
    <button class="navbar-toggler" type="button" data-bs-toggle="collapse" data-bs-target="#navbarSupportedContent" aria-controls="navbarSupportedContent" aria-expanded="false" aria-label="Toggle navigation">
      <span class="navbar-toggler-icon"></span>
    </button>
    <div class="collapse navbar-collapse" id="navbarSupportedContent">
      <ul class="navbar-nav me-auto mb-2 mb-lg-0">
        <li class="nav-item">
          <a class="nav-link active" aria-current="page" href="#">Home</a>
        </li>
        <li class="nav-item">
          <a class="nav-link" href="#">Link</a>
        </li>
        <li class="nav-item dropdown">
          <a class="nav-link dropdown-toggle" href="#" id="navbarDropdown" role="button" data-bs-toggle="dropdown" aria-expanded="false">
            Dropdown
          </a>
          <ul class="dropdown-menu" aria-labelledby="navbarDropdown">
            <li><a class="dropdown-item" href="#">Action</a></li>
            <li><a class="dropdown-item" href="#">Another action</a></li>
            <li><hr class="dropdown-divider"></li>
            <li><a class="dropdown-item" href="#">Something else here</a></li>
          </ul>
        </li>
        <li class="nav-item">
          <a class="nav-link disabled" href="#" tabindex="-1" aria-disabled="true">Disabled</a>
        </li>
      </ul>
      <form class="d-flex">
        <input class="form-control me-2" type="search" placeholder="Search" aria-label="Search">
        <button class="btn btn-outline-success" type="submit">Search</button>
      </form>
    </div>
  </div>
</nav>

app/views/layouts/_notifications.html.erb
<% if alert || notice %>
  <div class="container mt-5 text-center">
    <% if alert %>
      <div class="alert alert-warning" role="alert">
        <%= alert %>
      </div>
    <% end %>
    <% if notice %>
      <div class="alert alert-success" role="alert">
        <%= notice %>
      </div>
    <% end %>
  </div>
<% end %>

app/views/layouts/_notificatons.html.erb
<% if alert || notice %>
  <div class="container mt-5 text-center">
    <% if alert %>
      <div class="alert alert-warning" role="alert">
        <%= alert %>
      </div>
    <% end %>
    <% if notice %>
      <div class="alert alert-success" role="alert">
        <%= notice %>
      </div>
    <% end %>
  </div>
<% end %>

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
  <head>
    <title>Trader</title>
    <meta name="viewport" content="width=device-width,initial-scale=1">
    <%= csrf_meta_tags %>
    <%= csp_meta_tag %>

    <%= stylesheet_link_tag 'application', media: 'all', 'data-turbolinks-track': 'reload' %>
    <%= javascript_pack_tag 'application', 'data-turbolinks-track': 'reload' %>
  </head>
  <body>

    <%= render "layouts/navbar" %>
    <%= render "layouts/notifications" %>
    <%= yield %>
    
  </body>
</html>

app/views/welcome/index.html.erb
<h1>hi it will track it for you</h1>
<p>Find me in app/views/welcome/index.html.erb</p>
<%= link_to 'log out', destroy_customer_session_path, method: :delete %>
<%= javascript_pack_tag 'my_js' %>

app/views/welcome/index.js.erb
console.log('test in index.js')